destination: _public
encoding: utf-8

collections:
  stuff:
    output: true
    permalink: /stuff/:name
  projects:
    output: true
    permalink: /stuff/project/:name

url: https://camk.co

plugins:
  - jekyll-last-modified-at
  - jekyll-sitemap
