destination: _public
encoding: utf-8

collections:
  stuff:
    output: true
    permalink: /stuff/:name
  projects:
    output: true
    permalink: /stuff/project/:name
  posts:
    output: true
    permalink: /stuff/posts/:year/:month/:day/:title
    
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      is_post: true

url: https://camk.co

plugins:
  - jekyll-last-modified-at
  - jekyll-sitemap
